# **Machine Learning Week 3**
---
> Introduction to Machine Learning <br>
> Sekolah Data, Pacmann

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
plt.rcParams.update({'font.size': 16})

---
## Sampling

- Lakukan sampling acak dengan `<dataframe>.sample()`

In [3]:
# Buat data yang ingin di-sampling
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
y = (2*x + 3)**2 # untuk x = 1, 2*1+3 = 5**2 = 25

data = pd.DataFrame({"x": x,
                     "y": y})

data

    x    y
0   1   25
1   2   49
2   3   81
3   4  121
4   5  169
5   6  225
6   7  289
7   8  361
8   9  441
9  10  529

In [6]:
# Lakukan sampling sederhana
# Sampling TANPA pengembalian
n_sample = 5
data.sample(n = n_sample) # masih bentuk data frame

   x    y
0  1   25
3  4  121
4  5  169
1  2   49
8  9  441

**^ tiap kita run, mengeluarkan hasil output yang berbeda - beda**

In [7]:
# Lakukan 10 sampling
for i in range(10):
    data_sample = data.sample(n = n_sample) # n = 5, liat atas lagi
    index_data_sample = data_sample.index.to_list() # dari dataframe ke list

    print(f"Index sample ke-{i+1} : {index_data_sample}")

Index sample ke-1 : [0, 8, 5, 2, 7]
Index sample ke-2 : [0, 2, 9, 4, 5]
Index sample ke-3 : [3, 2, 5, 8, 6]
Index sample ke-4 : [4, 8, 5, 6, 3]
Index sample ke-5 : [6, 0, 5, 9, 8]
Index sample ke-6 : [7, 6, 9, 1, 8]
Index sample ke-7 : [7, 1, 3, 0, 6]
Index sample ke-8 : [5, 0, 1, 9, 3]
Index sample ke-9 : [8, 2, 5, 3, 6]
Index sample ke-10 : [2, 4, 7, 5, 6]

**^ diatas cuman ngambil index ya, kaloo mau secara lengkap dengan index dan data kolom `x` dan `y`, bisa kaya gini :**

In [12]:
# Lakukan 10 sampling
for i in range(10):
    data_sample = data.sample(n = n_sample)
    
    # Langsung cetak seluruh tabel data_sample-nya
    print(f"Index sample ke-{i+1} :")
    print(data_sample)
    print("--------------------") # Pemisah agar rapi

Index sample ke-1 :
   x    y
3  4  121
8  9  441
0  1   25
2  3   81
1  2   49
--------------------
Index sample ke-2 :
   x    y
8  9  441
4  5  169
0  1   25
1  2   49
2  3   81
--------------------
Index sample ke-3 :
    x    y
9  10  529
0   1   25
8   9  441
1   2   49
5   6  225
--------------------
Index sample ke-4 :
   x    y
4  5  169
2  3   81
7  8  361
5  6  225
6  7  289
--------------------
Index sample ke-5 :
    x    y
9  10  529
8   9  441
7   8  361
6   7  289
5   6  225
--------------------
Index sample ke-6 :
   x    y
7  8  361
3  4  121
5  6  225
2  3   81
1  2   49
--------------------
Index sample ke-7 :
   x    y
2  3   81
0  1   25
3  4  121
5  6  225
8  9  441
--------------------
Index sample ke-8 :
    x    y
4   5  169
9  10  529
5   6  225
1   2   49
6   7  289
--------------------
Index sample ke-9 :
    x    y
1   2   49
6   7  289
7   8  361
4   5  169
9  10  529
--------------------
Index sample ke-10 :
    x    y
5   6  225
0   1   25
6   7  289
9  10  529
3   4  121
--------------------

Sebenarnya **ide dari Resampling mirip Sampling diatas** ^, hanya saja kita **menambahkan argumen `'Replace = True'`**. Maksudnya adalah, **data acak tadi boleh ada angka yang muncul lagi. **

kalo ga paham, diatas kan kalo udah muncul angka 2, ga muncul lagi di angka selanjutnya. `[0, 8, 5, 2, 7]`

nah dengan argumen `'Replace = True'`, angka 2 bisa muncul lagi. `[5, 3, 7, 2, 2]`

In [10]:
# Lakukan sampling sederhana
# Sampling DENGAN pengembalian
n_sample = 5
data.sample(n = n_sample,
            replace = True)

   x    y
2  3   81
2  3   81
3  4  121
1  2   49
5  6  225

In [11]:
# Lakukan 10 sampling
for i in range(10):
    data_sample = data.sample(n = n_sample, replace = True)
    index_data_sample = data_sample.index.to_list()

    print(f"Index sample ke-{i+1} : {index_data_sample}")

Index sample ke-1 : [9, 2, 0, 1, 0]
Index sample ke-2 : [1, 0, 7, 9, 4]
Index sample ke-3 : [7, 6, 0, 9, 0]
Index sample ke-4 : [5, 3, 7, 2, 2]
Index sample ke-5 : [5, 6, 1, 7, 0]
Index sample ke-6 : [7, 8, 0, 7, 5]
Index sample ke-7 : [5, 5, 7, 9, 1]
Index sample ke-8 : [8, 3, 3, 8, 6]
Index sample ke-9 : [3, 3, 6, 6, 4]
Index sample ke-10 : [2, 9, 7, 7, 4]